### ISSUE TITLE
TypeError: 'NoneType' object is not callable, correlation plot

### ISSUE THREAD

**Issue by Smedvede** [ioerger/transit2#1]
Hi!

When trying to generate a correlation plot using cholesterol_glycerol.transit data in GUI I received an error message:

[transit_tools:__enter__()] Starting Corrplot analysis 
[transit_tools:calc_gene_means()] Normalizing using: TTR 
  File "/Users/smedvede/transit2/src/pytransit/components/panel_helpers.py", line 698, in run_wrapper
    method_instance = from_gui_function(gui.frame)
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 243, in from_gui
    Method.output(
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 319, in output
    g.figure.savefig(output_path, bbox_inches='tight')
  File "/Users/smedvede/transit2/src/pytransit/specific_tools/transit_tools.py", line 278, in __exit__
    raise error
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 279, in output
    position_hash[col] = FloatVector([x[i] for x in means])

'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/smedvede/transit2/src/pytransit/components/panel_helpers.py", line 705, in run
    thread = threading.Thread(target=run_wrapper())
  File "/Users/smedvede/transit2/src/pytransit/components/panel_helpers.py", line 698, in run_wrapper
    method_instance = from_gui_function(gui.frame)
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 243, in from_gui
    Method.output(
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 319, in output
    g.figure.savefig(output_path, bbox_inches='tight')
  File "/Users/smedvede/transit2/src/pytransit/specific_tools/transit_tools.py", line 278, in __exit__
    raise error
  File "/Users/smedvede/transit2/src/pytransit/methods/corrplot.py", line 279, in output
    position_hash[col] = FloatVector([x[i] for x in means])
TypeError: 'NoneType' object is not callable

<img width="1013" alt="изображение" src="https://github.com/ioerger/transit2/assets/128424204/171f6fba-274c-4d8e-a3e0-169b57c18c5e">

Best wishes,
Sofia

**Comment by ioerger2** [comment]
Thanks for reporting this.
The bug should now be fixed in release v1.0.7 of Transit2.
It had to do with a dependency on rpy2.
If you have further problems, please let me know.

Tom Ioerger
ioerger@cs.tamu.edu
